version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: attendance_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_attendance
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Simple test application
  app:
    image: node:18-alpine
    container_name: attendance_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=student_attendance
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache python3 make g++ &&
        npm install &&
        echo 'Testing basic server startup...' &&
        npx tsx -e '
          import express from \"express\";
          const app = express();
          app.get(\"/\", (req, res) => res.send(\"Hello World!\"));
          app.get(\"/api/health\", (req, res) => res.json({status: \"ok\", timestamp: new Date().toISOString()}));
          app.listen(3000, \"0.0.0.0\", () => console.log(\"Test server running on port 3000\"));
        '
      "

volumes:
  db_data: