version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: attendance_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_attendance
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Application
  app:
    build: .
    container_name: attendance_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=student_attendance
      - SESSION_SECRET=your-session-secret-here
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared

volumes:
  db_data: