@echo off
echo Dropping and recreating database...
"C:\Program Files\MariaDB 10.6\bin\mysql" -u root -p -e "DROP DATABASE IF EXISTS student_attendance; CREATE DATABASE student_attendance;"
echo Re-applying schema...
"C:\Program Files\MariaDB 10.6\bin\mysql" -u root -p student_attendance < server\schema.sql
echo Re-running seed script...
npx tsx server\seed.ts
echo Done! 